### ISSUE TITLE
Getting a compile error on Linux Ubuntu 64-bit

### ISSUE THREAD

**Issue by xelerance** [massar/sixxsd#1]
==== SixXSd - SixXS Daemon ====
Building  : SixXSd
Copyright : (C) Copyright SixXS 2000-2015 All Rights Reserved
Version   : 4.0
Release   : 2015.10.12
Options   :  -DOPTIMIZE
OS        : Linux 64-bit
Compiler  : cc 5.4.0
* Compiling sixxsd.o
sixxsd.c: In function ‘main’:
sixxsd.c:551:3: warning: ignoring return value of ‘freopen’, declared with attribute warn_unused_result [-Wunused-result]
   freopen("/dev/null", "r", stdin);
   ^
sixxsd.c:552:3: warning: ignoring return value of ‘freopen’, declared with attribute warn_unused_result [-Wunused-result]
   freopen("/dev/null", "w", stdout);
   ^
sixxsd.c:553:3: warning: ignoring return value of ‘freopen’, declared with attribute warn_unused_result [-Wunused-result]
   freopen("/dev/null", "w", stderr);
   ^
* Compiling ayiya.o
* Compiling checksum.o
* Compiling common.o
In file included from /usr/include/x86_64-linux-gnu/sys/socket.h:38:0,
                 from platform.h:67,
                 from sixxsd.h:62,
                 from common.c:7:
common.c: In function ‘recv_from_to’:
common.c:83:32: error: invalid application of ‘sizeof’ to incomplete type ‘struct in6_pktinfo’
   char cmsg6[CMSG_SPACE(sizeof(struct in6_pktinfo))];
                                ^
common.c:124:56: error: dereferencing pointer to incomplete type ‘struct in6_pktinfo’
    memcpy(&((struct sockaddr_in6*)to)->sin6_addr, &pkt6->ipi6_addr, sizeof(pkt6->ipi6_addr));
                                                        ^
Makefile:90: recipe for target 'common.o' failed
make[1]: *** [common.o] Error 1
Makefile:263: recipe for target 'all' failed
make: *** [all] Error 2

Perhaps missing a .h file ?

**Comment by massar** [comment]
I don't have any Ubuntu's handy; but just compiled on Debian 9.4 with the two commits just pushed and then it nicely compiles.

Include definitions change over time....

**Comment by xelerance** [comment]
That was perfect.

For anyone else interested in compiling this code on Ubuntu 16.04:

```
apt-get install libmysqlclient-dev librrd-dev
make all
```
